ktor:
  application:
    modules:
      - net.polvott.ApplicationKt.module
  deployment:
    port: 8080
jwt:
#jwt 2048
  issuerA:
    privateKey: "MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQDt31V4gGasFdeONusmWngMbvd+4AMM25pNuniEzpoBI58555tPvcOu7xk+1D6EilMWu+tbO39HXnkjR9fJdX1jch/jWZAmfTCet8osEK0HnU9PRp1DmNG9XHwaHb76O5RJfWjlzcQAiiPZBeeMoL/hA/lDeRAyT57jZbHiqnHZkCm3162rMA0888gGT4UFNjuZhUiklkQmEx6E4mVJtEZOCMCGjjL/VCLigiJnSdQNAHUnddAMLPnUr4OT5epKWufmAdQkJgLg/3c/sJHOiiXnYR430beTnl4gHYAcQUEQXoW4ZXkyGDyVV/m2vcxTs1IzRRqqM3fnoMtk8qwNlYmxAgMBAAECggEAJWQ0aBntnxewh8M76Tj9DZ30hftKRMn7skPhcFBA/B8whyZ65FOE6umHHeMOJWvQTiQMWzh53ur2VCSVwoNsn5EP0H9CfhJdbgL0+EKczbQdhJgp3gzWd2jjfIAi25c5ouhgRgi3dTWXF0/AIKZ00wxQBppaq0CXI3wCX4osavwv5C39N2N5/eVmz/qVvetDoPeL5s+arvbvmI08MSQRGGKkSv+ajUJ+D0dTGyAVvYvttOPLJCzXSbACxIWzUgwKk/US1g/42Wy6owmpEB5qY+C6OIzkJSRtyYvGMF/IuhtZab+SSi6GWZGtrE8imNfxcXbPgfY9LkAsYgskI3sAswKBgQD/nMqrX2qE/1OZzgFjg06uhqI5p4KXz9IR1q6vvWUWOYYoxLSUIToK0ZQr1UCA58BRqW8VL3RW88X4SwzcLTzwIVu7rG0D28upmoDIGzpwzi8pIcScTj2DVRW0N7PxLZ1INWYC+OJPWvM/xSNWPRx2f+Bpdwe9xmlmmeSEtEQ4FwKBgQDuO6grpBu+Z4NP6UGEqJuu2O65h23ETZDqbvRtR3wweHrOYue3sBMYTtI6tuJXuy/QcKP0a2oJasF7oeYAcKuPSm3KbVtQZv5ERsMM4SS6raAGCyB58b+Gw3yp/3cUzbesLKP8+4q1stUIpvJLthmfuTwrwMfG7HBQN1esAM+hdwKBgCI/ktQlY7NQNpZcCMmZlVhDB8drz06h9MaZGizH1pyEtpoNyRgz34AFlrHMz+i1pIoMhqqzAgaIgRUEkUOK+ChAf/cEYlLrBz3BStIE++6TYbREJwC+ZvWK1+6erAh7kSBUr0dkq4XwbLk1o8dxRrgF6D6ZSTs/M24g3oJ9WMqfAoGALuG8kYIFF65FMBemFhYcNQdpy0b0efoNt6TIIy07Kkq7WBwsn4Bd8Z2pT3aoCj3DBhD0ouf0gQ/qLYtJuPJzQIqUGo70tljeVs9aGRHBaZ87a5UK+hRx7XJQ+R9V7tkg+Rf72ZAi1ujvdXltGysl1cHdLnsMlX/4BkEt1qJ+ObcCgYASVkWUogGtHYtGa76KksWLj15i+s3VQmn8SsFQ2uC0j54fKtLn+2n3bYWnsxTOcsQUga4U3yfX5KJn7i6peeiF2+ge2MW3vc1CMT0amfUh1ZmEqO4TmdlW2zD17AzjJJcsAex5LZrOqNBfwE+yGwxPbfqJ5lT/nKFWu1Bim6x8JQ=="
    domain: "http://localhost:8080/"
    audience: "http://localhost:8080"
    realm: "ktor sample app"
    issuer: "http://localhost:8080/issuerA"

# short
  issuerB:
    privateKey: "MIIBVgIBADANBgkqhkiG9w0BAQEFAASCAUAwggE8AgEAAkEAwFPVl7xLVD9sR+UXYNOMmLykMXZv5TIaC3DsyrX1ox2gWGksTJ+6P3WrJKZMb6lVhv7ZJ4xKXYTgVjkvXHfNZwIDAQABAkEAiveIbB0X6QXyvXghDkuNWYdktIC5lUhAXWf5EPetR3ANZoqztW/HM5yjhsWUxCXoFD59bEDL2OXaA3T4Di6soQIhAOzSFbARBsjOqja9pX/wZ3kDMhkf2YTfOA8/gRUNsj+fAiEAz+dKCLm8L/iCldN0QPelsyhN1qqw1eWnw44+FEHpfTkCIGvZiRLzzhkpNQ9U8sf/HcBYmjoi7Ra76XXYP9rsr96VAiEAh5tKK/TSLcv/iTB6hKHDn98rHlkJrQr16VUPYvE3FekCIQCmyCRjWGOMEsuKRBGi4Wu2tXUZv3qhAMRtbIoLeUQB5w"
    domain: "http://localhost:8080/"
    audience: "http://localhost:8080"
    realm: "ktor sample app"
    issuer: "http://localhost:8080/issuerB"
